### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kneknew** [sudo-harun/dotfiles#1]
I ran the install.sh file with the command "./install.sh" but after completing it just changed the shell to zsh and nothing more happened

**Comment by sudo-harun** [comment]
You have to manually launch Hyprland by typing `Hyprland` then hitting Enter in TTY.

I will add a `.zsh_login` soon to automatically launch Hyprland after login from TTY.

There is also a post install script for aliases, setting up bluetooth and setting up terminal colours depending on which branch you are using. You can comment out parts you don't want then do `./post-install.sh`.

**Comment by sudo-harun** [comment]
Also, you will need to manually set font, GTK theme using `nwg-look-bin` (can find in wofi by seaching for 'GTK Settings') and set wallpaper manually using `waypaper` (launch in terminal with `waypaper` command).

Will add all necessary information to README.md soon, although I never intended anyone to actually use my install script. Will improve that too when I have the time.
